#!/bin/sh

IFS=":"

# show usage and exit
usage() {
	echo "usage: agenda [-cet] [-w WEEKS]" >&2
	exit 1
}

# replace $HOME with ~
striphome() {
	awk '
		BEGIN {
			HOME = ENVIRON["HOME"]
			PROJ = ENVIRON["PROJDIR"]
		}
		{
			if (PROJ && match($0, HOME "/[^:]+")) {
				s = substr($0, RSTART + length(PROJ) + 1, RLENGTH)
				sub(/\/[^\/]*$/, "", s)
				print substr($0, 1, RSTART - 1) s substr($0, RSTART + RLENGTH)
			} else if (HOME && match($0, HOME "[^:]+")) {
				s = substr($0, RSTART + length(HOME), RLENGTH)
				sub(/\/[^\/]*$/, "", s)
				print substr($0, 1, RSTART - 1) "~" s substr($0, RSTART + RLENGTH)
			} else {
				print
			}
		}
	'
}

# parse command-line options
week=0
while getopts 'cdetw:' c
do
	case "$c" in
	c)
		calendar=1
		;;
	d)
		todoopts="-d"
		;;
	e)
		events=1
		;;
	t)
		tasks=1
		;;
	w)
		week="$OPTARG"
		;;
	*)
		usage
		;;
	esac
done
shift $(( OPTIND - 1 ))
if [ "$calendar" -eq 0 ] && [ "$events" -eq 0 ] && [ "$tasks" -eq 0 ]
then
	calendar=1
	events=1
	tasks=1
fi

# compute time
time="$(( $(date +%s) + week * 7 * 24 * 60 * 60 ))"
mday="$(perl -le 'my $n = (localtime($ARGV[0]))[3]; print $n' "$time")"
month="$(perl -le 'my $n = (localtime($ARGV[0]))[4] + 1; print $n' "$time")"
year="$(perl -le 'my $n = (localtime($ARGV[0]))[5] + 1900; print $n' "$time")"

# display calendar
if [ "$calendar" -ne 0 ]
then
	cal -m "$month" "$year" |\
	sed -r "$(printf '3,$ s/[[:<:]]%s[[:>:]]/\033[7m&\033[0m/' "$mday")"
	echo ""
fi

w="$(perl -le 'my $n = (localtime($ARGV[0]))[6]; print $n' "$time")"
[ "$w" -eq 0 ] && w=7
time="$(( time - (w - 1) * 24 * 60 * 60 ))"
mday="$(perl -le 'my $n = (localtime($ARGV[0]))[3]; print $n' "$time")"
month="$(perl -le 'my $n = (localtime($ARGV[0]))[4] + 1; print $n' "$time")"
year="$(perl -le 'my $n = (localtime($ARGV[0]))[5] + 1900; print $n' "$time")"

# display events
if [ "$events" -ne 0 ]
then
	echo "Events:"
	calendar -l -T"$year-$month-$mday" -n6 $CALENDAR | striphome
	echo ""
fi

# display tasks
if [ "$tasks" -ne 0 ]
then
	echo "Tasks:"
	todo $todoopts -l $TODO | striphome
fi

exit 0
